
create schema if not exists private;

create table if not exists private.avesso_economy_item_events (
  id bigint generated by default as identity primary key,
  event_type text not null check (
    event_type = any (array[
      'market_listing_created','market_listing_cancelled','market_listing_expired','market_purchase',
      'trade_created','trade_accepted','trade_rejected','trade_cancelled','trade_expired'
    ]::text[])
  ),
  actor_id uuid references public.profiles(id) on delete set null,
  from_user_id uuid references public.profiles(id) on delete set null,
  to_user_id uuid references public.profiles(id) on delete set null,
  item_id uuid references public.avesso_item_catalog(id) on delete set null,
  quantity integer check (quantity is null or quantity > 0),
  saldo_amount bigint check (saldo_amount is null or saldo_amount >= 0),
  market_listing_id uuid references public.avesso_market_listings(id) on delete set null,
  trade_offer_id uuid references public.avesso_trade_offers(id) on delete set null,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);
create index if not exists avesso_economy_item_events_created_idx on private.avesso_economy_item_events(created_at desc);
create index if not exists avesso_economy_item_events_item_idx on private.avesso_economy_item_events(item_id, created_at desc);
create index if not exists avesso_economy_item_events_actor_idx on private.avesso_economy_item_events(actor_id, created_at desc);
create index if not exists avesso_economy_item_events_market_idx on private.avesso_economy_item_events(market_listing_id, created_at desc);
create index if not exists avesso_economy_item_events_trade_idx on private.avesso_economy_item_events(trade_offer_id, created_at desc);
revoke all on table private.avesso_economy_item_events from public, anon, authenticated;
revoke all on sequence private.avesso_economy_item_events_id_seq from public, anon, authenticated;


CREATE OR REPLACE FUNCTION public.avesso_market_buy(p_listing_id uuid)
 RETURNS boolean
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO ''
AS $function$
declare
  v_buyer uuid := (select auth.uid());
  v_listing public.avesso_market_listings%rowtype;
  v_escrow public.avesso_market_escrow%rowtype;
  v_mode text;
  v_balance bigint;
begin
  if v_buyer is null then raise exception 'authentication_required'; end if;

  select mode into v_mode
  from public.avesso_economy_settings
  where id='global';

  if coalesce(v_mode,'off') <> 'live' then
    raise exception 'economy_not_live';
  end if;

  select * into v_listing
  from public.avesso_market_listings
  where id=p_listing_id
  for update;

  if not found or v_listing.status <> 'active' then
    raise exception 'listing_not_available';
  end if;

  if v_listing.seller_id = v_buyer then
    raise exception 'cannot_buy_own_listing';
  end if;

  if v_listing.expires_at is not null and v_listing.expires_at <= now() then
    select * into v_escrow
    from public.avesso_market_escrow
    where listing_id = p_listing_id
    for update;

    if found then
      insert into public.avesso_user_inventory(
        user_id,item_id,quantity,acquisition_source,metadata
      )
      values(
        v_listing.seller_id,v_escrow.item_id,v_escrow.quantity,
        'market_expire',jsonb_build_object('listing_id',p_listing_id)
      )
      on conflict(user_id,item_id)
      do update set quantity = public.avesso_user_inventory.quantity + excluded.quantity;

      delete from public.avesso_market_escrow where listing_id=p_listing_id;
    end if;

    update public.avesso_market_listings
    set status='expired',updated_at=now()
    where id=p_listing_id;

    if found then
      insert into private.avesso_economy_item_events(
        event_type,actor_id,to_user_id,item_id,quantity,market_listing_id,metadata
      )
      values(
        'market_listing_expired',v_buyer,v_listing.seller_id,
        v_escrow.item_id,v_escrow.quantity,p_listing_id,'{}'::jsonb
      );
    end if;

    return false;
  end if;

  select * into v_escrow
  from public.avesso_market_escrow
  where listing_id=p_listing_id
  for update;

  if not found then raise exception 'escrow_missing'; end if;

  insert into public.avesso_wallets(user_id)
  values(v_buyer)
  on conflict(user_id) do nothing;

  insert into public.avesso_wallets(user_id)
  values(v_listing.seller_id)
  on conflict(user_id) do nothing;

  perform 1
  from public.avesso_wallets
  where user_id in(v_buyer,v_listing.seller_id)
  order by user_id
  for update;

  select balance into v_balance
  from public.avesso_wallets
  where user_id=v_buyer;

  if coalesce(v_balance,0) < v_listing.price_saldo then
    raise exception 'insufficient_saldo';
  end if;

  insert into public.avesso_wallet_ledger(
    user_id,transaction_type,rule_key,source_type,source_id,amount,idempotency_key,metadata
  )
  values(
    v_buyer,'transfer_out',null,'market_listing',p_listing_id::text,
    -v_listing.price_saldo::integer,
    'market:buy:out:'||p_listing_id::text,
    jsonb_build_object('seller_id',v_listing.seller_id)
  );

  insert into public.avesso_wallet_ledger(
    user_id,transaction_type,rule_key,source_type,source_id,amount,idempotency_key,metadata
  )
  values(
    v_listing.seller_id,'transfer_in',null,'market_listing',p_listing_id::text,
    v_listing.price_saldo::integer,
    'market:buy:in:'||p_listing_id::text,
    jsonb_build_object('buyer_id',v_buyer)
  );

  update public.avesso_wallets
  set balance=balance-v_listing.price_saldo,
      lifetime_spent=lifetime_spent+v_listing.price_saldo,
      updated_at=now()
  where user_id=v_buyer;

  update public.avesso_wallets
  set balance=balance+v_listing.price_saldo,
      lifetime_earned=lifetime_earned+v_listing.price_saldo,
      updated_at=now()
  where user_id=v_listing.seller_id;

  insert into public.avesso_user_inventory(
    user_id,item_id,quantity,acquisition_source,metadata
  )
  values(
    v_buyer,v_escrow.item_id,v_escrow.quantity,
    'market_purchase',
    jsonb_build_object('listing_id',p_listing_id,'seller_id',v_listing.seller_id)
  )
  on conflict(user_id,item_id)
  do update set quantity=public.avesso_user_inventory.quantity+excluded.quantity;

  delete from public.avesso_market_escrow
  where listing_id=p_listing_id;

  update public.avesso_market_listings
  set status='sold',buyer_id=v_buyer,sold_at=now(),updated_at=now()
  where id=p_listing_id;

  insert into private.avesso_economy_item_events(
    event_type,actor_id,from_user_id,to_user_id,item_id,quantity,saldo_amount,market_listing_id,metadata
  )
  values(
    'market_purchase',v_buyer,v_listing.seller_id,v_buyer,
    v_escrow.item_id,v_escrow.quantity,v_listing.price_saldo,p_listing_id,
    jsonb_build_object('seller_id',v_listing.seller_id)
  );

  return true;
end;
$function$
;

CREATE OR REPLACE FUNCTION public.avesso_market_cancel_listing(p_listing_id uuid)
 RETURNS boolean
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO ''
AS $function$
declare
  v_user uuid := (select auth.uid());
  v_listing public.avesso_market_listings%rowtype;
  v_escrow public.avesso_market_escrow%rowtype;
  v_event text;
begin
  if v_user is null then raise exception 'authentication_required'; end if;

  select * into v_listing
  from public.avesso_market_listings
  where id = p_listing_id
  for update;

  if not found or v_listing.seller_id <> v_user then
    raise exception 'listing_not_found';
  end if;

  if v_listing.status <> 'active' then
    return false;
  end if;

  select * into v_escrow
  from public.avesso_market_escrow
  where listing_id = p_listing_id
  for update;

  if not found then raise exception 'escrow_missing'; end if;

  insert into public.avesso_user_inventory(
    user_id,item_id,quantity,acquisition_source,metadata
  )
  values(
    v_user,v_escrow.item_id,v_escrow.quantity,
    case when v_listing.expires_at is not null and v_listing.expires_at <= now()
      then 'market_expire' else 'market_cancel' end,
    jsonb_build_object('listing_id',p_listing_id)
  )
  on conflict(user_id,item_id)
  do update set quantity = public.avesso_user_inventory.quantity + excluded.quantity;

  v_event := case when v_listing.expires_at is not null and v_listing.expires_at <= now()
    then 'market_listing_expired' else 'market_listing_cancelled' end;

  delete from public.avesso_market_escrow
  where listing_id = p_listing_id;

  update public.avesso_market_listings
  set status = case when v_event = 'market_listing_expired' then 'expired' else 'cancelled' end,
      updated_at = now()
  where id = p_listing_id;

  insert into private.avesso_economy_item_events(
    event_type,actor_id,to_user_id,item_id,quantity,market_listing_id,metadata
  )
  values(
    v_event,v_user,v_user,v_escrow.item_id,v_escrow.quantity,p_listing_id,'{}'::jsonb
  );

  return true;
end;
$function$
;

CREATE OR REPLACE FUNCTION public.avesso_market_create_listing(p_item_id uuid, p_quantity integer, p_price_saldo bigint, p_expires_at timestamp with time zone DEFAULT NULL::timestamp with time zone)
 RETURNS uuid
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO ''
AS $function$
declare
  v_user uuid := (select auth.uid());
  v_listing uuid;
  v_qty integer;
  v_item public.avesso_item_catalog%rowtype;
begin
  if v_user is null then raise exception 'authentication_required'; end if;
  if p_quantity is null or p_quantity <= 0 then raise exception 'invalid_quantity'; end if;
  if p_price_saldo is null or p_price_saldo <= 0 or p_price_saldo > 2147483647 then raise exception 'invalid_price'; end if;
  if p_expires_at is not null and p_expires_at <= now() then raise exception 'invalid_expiry'; end if;

  select * into v_item
  from public.avesso_item_catalog c
  where c.id = p_item_id and c.active = true;

  if not found or not v_item.tradable or v_item.soulbound then
    raise exception 'item_not_tradable';
  end if;

  if exists (
    select 1
    from public.avesso_market_listings l
    where l.seller_id = v_user and l.item_id = p_item_id and l.status = 'active'
  ) then
    raise exception 'active_listing_exists';
  end if;

  select i.quantity into v_qty
  from public.avesso_user_inventory i
  where i.user_id = v_user and i.item_id = p_item_id
  for update;

  if coalesce(v_qty, 0) < p_quantity then
    raise exception 'insufficient_inventory';
  end if;

  if v_qty = p_quantity then
    delete from public.avesso_user_inventory
    where user_id = v_user and item_id = p_item_id;
  else
    update public.avesso_user_inventory
    set quantity = quantity - p_quantity
    where user_id = v_user and item_id = p_item_id;
  end if;

  insert into public.avesso_market_listings(
    seller_id,item_id,quantity,price_saldo,expires_at
  )
  values(v_user,p_item_id,p_quantity,p_price_saldo,p_expires_at)
  returning id into v_listing;

  insert into public.avesso_market_escrow(listing_id,item_id,quantity)
  values(v_listing,p_item_id,p_quantity);

  insert into private.avesso_economy_item_events(
    event_type,actor_id,from_user_id,to_user_id,item_id,quantity,saldo_amount,market_listing_id,metadata
  )
  values(
    'market_listing_created',v_user,v_user,null,p_item_id,p_quantity,p_price_saldo,v_listing,
    jsonb_build_object('expires_at',p_expires_at)
  );

  return v_listing;
end;
$function$
;

CREATE OR REPLACE FUNCTION public.avesso_market_expire_listing(p_listing_id uuid)
 RETURNS boolean
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO ''
AS $function$
declare
  v_user uuid := (select auth.uid());
  v_listing public.avesso_market_listings%rowtype;
  v_escrow public.avesso_market_escrow%rowtype;
begin
  if v_user is null then raise exception 'authentication_required'; end if;

  select * into v_listing
  from public.avesso_market_listings
  where id = p_listing_id
  for update;

  if not found or v_listing.status <> 'active' then
    return false;
  end if;

  if v_listing.expires_at is null or v_listing.expires_at > now() then
    return false;
  end if;

  select * into v_escrow
  from public.avesso_market_escrow
  where listing_id = p_listing_id
  for update;

  if not found then raise exception 'escrow_missing'; end if;

  insert into public.avesso_user_inventory(
    user_id,item_id,quantity,acquisition_source,metadata
  )
  values(
    v_listing.seller_id,v_escrow.item_id,v_escrow.quantity,
    'market_expire',jsonb_build_object('listing_id',p_listing_id)
  )
  on conflict(user_id,item_id)
  do update set quantity = public.avesso_user_inventory.quantity + excluded.quantity;

  delete from public.avesso_market_escrow
  where listing_id = p_listing_id;

  update public.avesso_market_listings
  set status='expired',updated_at=now()
  where id=p_listing_id;

  insert into private.avesso_economy_item_events(
    event_type,actor_id,to_user_id,item_id,quantity,market_listing_id,metadata
  )
  values(
    'market_listing_expired',v_user,v_listing.seller_id,
    v_escrow.item_id,v_escrow.quantity,p_listing_id,'{}'::jsonb
  );

  return true;
end;
$function$
;

CREATE OR REPLACE FUNCTION public.avesso_trade_accept_offer(p_offer_id uuid)
 RETURNS boolean
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO ''
AS $function$
declare
  v_user uuid := (select auth.uid());
  v_offer public.avesso_trade_offers%rowtype;
  v_line record;
  v_owned integer;
begin
  if v_user is null then raise exception 'authentication_required'; end if;

  select * into v_offer
  from public.avesso_trade_offers
  where id=p_offer_id
  for update;

  if not found or v_offer.counterparty_id<>v_user then raise exception 'offer_not_found'; end if;
  if v_offer.status<>'pending' then return false; end if;

  if v_offer.expires_at is not null and v_offer.expires_at<=now() then
    for v_line in
      select item_id,quantity
      from public.avesso_trade_escrow
      where offer_id=p_offer_id
      order by item_id
      for update
    loop
      insert into public.avesso_user_inventory(
        user_id,item_id,quantity,acquisition_source,metadata
      )
      values(
        v_offer.proposer_id,v_line.item_id,v_line.quantity,
        'trade_expire',jsonb_build_object('offer_id',p_offer_id)
      )
      on conflict(user_id,item_id)
      do update set quantity=public.avesso_user_inventory.quantity+excluded.quantity;

      insert into private.avesso_economy_item_events(
        event_type,actor_id,to_user_id,item_id,quantity,trade_offer_id,metadata
      )
      values(
        'trade_expired',v_user,v_offer.proposer_id,
        v_line.item_id,v_line.quantity,p_offer_id,'{}'::jsonb
      );
    end loop;

    delete from public.avesso_trade_escrow where offer_id=p_offer_id;
    update public.avesso_trade_offers
    set status='expired',updated_at=now()
    where id=p_offer_id;
    return false;
  end if;

  for v_line in
    select item_id,quantity
    from public.avesso_trade_lines
    where offer_id=p_offer_id and side='request'
    order by item_id
  loop
    select quantity into v_owned
    from public.avesso_user_inventory
    where user_id=v_user and item_id=v_line.item_id
    for update;

    if coalesce(v_owned,0)<v_line.quantity then
      raise exception 'counterparty_inventory_changed';
    end if;
  end loop;

  for v_line in
    select item_id,quantity
    from public.avesso_trade_lines
    where offer_id=p_offer_id and side='request'
    order by item_id
  loop
    select quantity into v_owned
    from public.avesso_user_inventory
    where user_id=v_user and item_id=v_line.item_id
    for update;

    if v_owned=v_line.quantity then
      delete from public.avesso_user_inventory
      where user_id=v_user and item_id=v_line.item_id;
    else
      update public.avesso_user_inventory
      set quantity=quantity-v_line.quantity
      where user_id=v_user and item_id=v_line.item_id;
    end if;

    insert into public.avesso_user_inventory(
      user_id,item_id,quantity,acquisition_source,metadata
    )
    values(
      v_offer.proposer_id,v_line.item_id,v_line.quantity,
      'trade_received',
      jsonb_build_object('offer_id',p_offer_id,'from_user',v_user)
    )
    on conflict(user_id,item_id)
    do update set quantity=public.avesso_user_inventory.quantity+excluded.quantity;

    insert into private.avesso_economy_item_events(
      event_type,actor_id,from_user_id,to_user_id,item_id,quantity,trade_offer_id,metadata
    )
    values(
      'trade_accepted',v_user,v_user,v_offer.proposer_id,
      v_line.item_id,v_line.quantity,p_offer_id,jsonb_build_object('leg','request')
    );
  end loop;

  for v_line in
    select item_id,quantity
    from public.avesso_trade_escrow
    where offer_id=p_offer_id
    order by item_id
    for update
  loop
    insert into public.avesso_user_inventory(
      user_id,item_id,quantity,acquisition_source,metadata
    )
    values(
      v_user,v_line.item_id,v_line.quantity,
      'trade_received',
      jsonb_build_object('offer_id',p_offer_id,'from_user',v_offer.proposer_id)
    )
    on conflict(user_id,item_id)
    do update set quantity=public.avesso_user_inventory.quantity+excluded.quantity;

    insert into private.avesso_economy_item_events(
      event_type,actor_id,from_user_id,to_user_id,item_id,quantity,trade_offer_id,metadata
    )
    values(
      'trade_accepted',v_user,v_offer.proposer_id,v_user,
      v_line.item_id,v_line.quantity,p_offer_id,jsonb_build_object('leg','offer')
    );
  end loop;

  delete from public.avesso_trade_escrow where offer_id=p_offer_id;

  update public.avesso_trade_offers
  set status='accepted',accepted_at=now(),updated_at=now()
  where id=p_offer_id;

  return true;
end;
$function$
;

CREATE OR REPLACE FUNCTION public.avesso_trade_cancel_offer(p_offer_id uuid)
 RETURNS boolean
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO ''
AS $function$
declare
  v_user uuid := (select auth.uid());
  v_offer public.avesso_trade_offers%rowtype;
  v_row record;
begin
  if v_user is null then raise exception 'authentication_required'; end if;

  select * into v_offer
  from public.avesso_trade_offers
  where id=p_offer_id
  for update;

  if not found or v_offer.proposer_id<>v_user then raise exception 'offer_not_found'; end if;
  if v_offer.status<>'pending' then return false; end if;

  for v_row in
    select item_id,quantity
    from public.avesso_trade_escrow
    where offer_id=p_offer_id
    order by item_id
    for update
  loop
    insert into public.avesso_user_inventory(
      user_id,item_id,quantity,acquisition_source,metadata
    )
    values(
      v_user,v_row.item_id,v_row.quantity,
      'trade_cancel',jsonb_build_object('offer_id',p_offer_id)
    )
    on conflict(user_id,item_id)
    do update set quantity=public.avesso_user_inventory.quantity+excluded.quantity;

    insert into private.avesso_economy_item_events(
      event_type,actor_id,to_user_id,item_id,quantity,trade_offer_id,metadata
    )
    values(
      'trade_cancelled',v_user,v_user,v_row.item_id,v_row.quantity,p_offer_id,'{}'::jsonb
    );
  end loop;

  delete from public.avesso_trade_escrow where offer_id=p_offer_id;

  update public.avesso_trade_offers
  set status='cancelled',updated_at=now()
  where id=p_offer_id;

  return true;
end;
$function$
;

CREATE OR REPLACE FUNCTION public.avesso_trade_create_offer(p_counterparty_id uuid, p_offer jsonb, p_request jsonb, p_note text DEFAULT ''::text, p_expires_at timestamp with time zone DEFAULT NULL::timestamp with time zone)
 RETURNS uuid
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO ''
AS $function$
declare
  v_user uuid := (select auth.uid());
  v_offer_id uuid;
  v_line jsonb;
  v_item_id uuid;
  v_quantity integer;
  v_owned integer;
begin
  if v_user is null then raise exception 'authentication_required'; end if;
  if p_counterparty_id is null or p_counterparty_id=v_user then raise exception 'invalid_counterparty'; end if;
  if not exists(select 1 from public.profiles where id=p_counterparty_id) then raise exception 'counterparty_not_found'; end if;
  if p_expires_at is not null and p_expires_at<=now() then raise exception 'invalid_expiry'; end if;
  if jsonb_typeof(p_offer)<>'array' or jsonb_array_length(p_offer)=0 then raise exception 'empty_offer'; end if;
  if jsonb_typeof(p_request)<>'array' or jsonb_array_length(p_request)=0 then raise exception 'empty_request'; end if;

  insert into public.avesso_trade_offers(proposer_id,counterparty_id,note,expires_at)
  values(v_user,p_counterparty_id,left(coalesce(p_note,''),280),p_expires_at)
  returning id into v_offer_id;

  for v_line in select * from jsonb_array_elements(p_offer) loop
    v_item_id := (v_line->>'item_id')::uuid;
    v_quantity := (v_line->>'quantity')::integer;
    if v_quantity<=0 then raise exception 'invalid_quantity'; end if;

    if not exists(
      select 1 from public.avesso_item_catalog c
      where c.id=v_item_id and c.active and c.tradable and not c.soulbound
    ) then raise exception 'item_not_tradable'; end if;

    select quantity into v_owned
    from public.avesso_user_inventory
    where user_id=v_user and item_id=v_item_id
    for update;

    if coalesce(v_owned,0)<v_quantity then raise exception 'insufficient_inventory'; end if;

    if v_owned=v_quantity then
      delete from public.avesso_user_inventory
      where user_id=v_user and item_id=v_item_id;
    else
      update public.avesso_user_inventory
      set quantity=quantity-v_quantity
      where user_id=v_user and item_id=v_item_id;
    end if;

    insert into public.avesso_trade_lines(offer_id,side,item_id,quantity)
    values(v_offer_id,'offer',v_item_id,v_quantity);

    insert into public.avesso_trade_escrow(offer_id,item_id,quantity)
    values(v_offer_id,v_item_id,v_quantity);
  end loop;

  for v_line in select * from jsonb_array_elements(p_request) loop
    v_item_id := (v_line->>'item_id')::uuid;
    v_quantity := (v_line->>'quantity')::integer;
    if v_quantity<=0 then raise exception 'invalid_quantity'; end if;

    if not exists(
      select 1 from public.avesso_item_catalog c
      where c.id=v_item_id and c.active and c.tradable and not c.soulbound
    ) then raise exception 'item_not_tradable'; end if;

    insert into public.avesso_trade_lines(offer_id,side,item_id,quantity)
    values(v_offer_id,'request',v_item_id,v_quantity);
  end loop;

  insert into private.avesso_economy_item_events(
    event_type,actor_id,from_user_id,to_user_id,trade_offer_id,metadata
  )
  values(
    'trade_created',v_user,v_user,p_counterparty_id,v_offer_id,
    jsonb_build_object('offer',p_offer,'request',p_request,'note',left(coalesce(p_note,''),280))
  );

  return v_offer_id;
end;
$function$
;

CREATE OR REPLACE FUNCTION public.avesso_trade_expire_offer(p_offer_id uuid)
 RETURNS boolean
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO ''
AS $function$
declare
  v_user uuid := (select auth.uid());
  v_offer public.avesso_trade_offers%rowtype;
  v_row record;
begin
  if v_user is null then raise exception 'authentication_required'; end if;

  select * into v_offer
  from public.avesso_trade_offers
  where id=p_offer_id
  for update;

  if not found or v_offer.status<>'pending' then return false; end if;
  if v_offer.expires_at is null or v_offer.expires_at>now() then return false; end if;

  for v_row in
    select item_id,quantity
    from public.avesso_trade_escrow
    where offer_id=p_offer_id
    order by item_id
    for update
  loop
    insert into public.avesso_user_inventory(
      user_id,item_id,quantity,acquisition_source,metadata
    )
    values(
      v_offer.proposer_id,v_row.item_id,v_row.quantity,
      'trade_expire',jsonb_build_object('offer_id',p_offer_id)
    )
    on conflict(user_id,item_id)
    do update set quantity=public.avesso_user_inventory.quantity+excluded.quantity;

    insert into private.avesso_economy_item_events(
      event_type,actor_id,to_user_id,item_id,quantity,trade_offer_id,metadata
    )
    values(
      'trade_expired',v_user,v_offer.proposer_id,
      v_row.item_id,v_row.quantity,p_offer_id,'{}'::jsonb
    );
  end loop;

  delete from public.avesso_trade_escrow where offer_id=p_offer_id;

  update public.avesso_trade_offers
  set status='expired',updated_at=now()
  where id=p_offer_id;

  return true;
end;
$function$
;

CREATE OR REPLACE FUNCTION public.avesso_trade_reject_offer(p_offer_id uuid)
 RETURNS boolean
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO ''
AS $function$
declare
  v_user uuid := (select auth.uid());
  v_offer public.avesso_trade_offers%rowtype;
  v_row record;
begin
  if v_user is null then raise exception 'authentication_required'; end if;

  select * into v_offer
  from public.avesso_trade_offers
  where id=p_offer_id
  for update;

  if not found or v_offer.counterparty_id<>v_user then raise exception 'offer_not_found'; end if;
  if v_offer.status<>'pending' then return false; end if;

  for v_row in
    select item_id,quantity
    from public.avesso_trade_escrow
    where offer_id=p_offer_id
    order by item_id
    for update
  loop
    insert into public.avesso_user_inventory(
      user_id,item_id,quantity,acquisition_source,metadata
    )
    values(
      v_offer.proposer_id,v_row.item_id,v_row.quantity,
      'trade_rejected',jsonb_build_object('offer_id',p_offer_id)
    )
    on conflict(user_id,item_id)
    do update set quantity=public.avesso_user_inventory.quantity+excluded.quantity;

    insert into private.avesso_economy_item_events(
      event_type,actor_id,to_user_id,item_id,quantity,trade_offer_id,metadata
    )
    values(
      'trade_rejected',v_user,v_offer.proposer_id,
      v_row.item_id,v_row.quantity,p_offer_id,'{}'::jsonb
    );
  end loop;

  delete from public.avesso_trade_escrow where offer_id=p_offer_id;

  update public.avesso_trade_offers
  set status='rejected',updated_at=now()
  where id=p_offer_id;

  return true;
end;
$function$
;

revoke execute on function public.avesso_market_expire_listing(uuid) from public, anon;
revoke execute on function public.avesso_trade_expire_offer(uuid) from public, anon;
grant execute on function public.avesso_market_expire_listing(uuid) to authenticated;
grant execute on function public.avesso_trade_expire_offer(uuid) to authenticated;
