-- AVESSO // Economia de Saldo & Recompensas v1 — shadow mode
-- Aplicada no Supabase em 2026-10-04.
-- Fundação oculta: nenhuma UI pública depende destas tabelas ainda.

create schema if not exists private;
revoke all on schema private from public, anon, authenticated;

create table public.avesso_economy_settings (
  id text primary key default 'global' check (id='global'),
  mode text not null default 'shadow' check (mode in ('off','shadow','live')),
  global_daily_cap integer not null default 180 check (global_daily_cap >= 0),
  presence_block_seconds integer not null default 1800 check (presence_block_seconds between 300 and 7200),
  active_window_seconds integer not null default 120 check (active_window_seconds between 30 and 600),
  updated_at timestamptz not null default now()
);

create table public.avesso_reward_rules (
  rule_key text primary key check (rule_key ~ '^[a-z0-9_]{2,60}$'),
  label text not null check (char_length(label) between 2 and 100),
  category text not null check (category ~ '^[a-z0-9_]{2,40}$'),
  base_amount integer not null check (base_amount >= 0),
  daily_cap integer not null default 0 check (daily_cap >= 0),
  cooldown_seconds integer not null default 0 check (cooldown_seconds >= 0),
  multiplier_eligible boolean not null default true,
  counts_toward_daily_cap boolean not null default true,
  counts_toward_pulse boolean not null default true,
  enabled boolean not null default true,
  config jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.avesso_wallets (
  user_id uuid primary key references public.profiles(id) on delete cascade,
  balance bigint not null default 0 check (balance >= 0),
  lifetime_earned bigint not null default 0 check (lifetime_earned >= 0),
  lifetime_spent bigint not null default 0 check (lifetime_spent >= 0),
  updated_at timestamptz not null default now()
);

create table public.avesso_wallet_ledger (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  transaction_type text not null check (transaction_type in ('earn','spend','transfer_in','transfer_out','reversal','admin_adjustment')),
  rule_key text references public.avesso_reward_rules(rule_key) on delete restrict,
  source_type text not null check (char_length(source_type) between 1 and 80),
  source_id text not null check (char_length(source_id) between 1 and 180),
  amount integer not null check (amount <> 0),
  idempotency_key text not null unique check (char_length(idempotency_key) between 3 and 260),
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);
create index avesso_wallet_ledger_user_created_idx on public.avesso_wallet_ledger(user_id,created_at desc);
create index avesso_wallet_ledger_user_rule_created_idx on public.avesso_wallet_ledger(user_id,rule_key,created_at desc);

create table public.avesso_activity_sessions (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.profiles(id) on delete cascade,
  started_at timestamptz not null default now(),
  last_active_at timestamptz not null default now(),
  last_heartbeat_at timestamptz not null default now(),
  qualified_seconds integer not null default 0 check (qualified_seconds >= 0),
  rewarded_blocks integer not null default 0 check (rewarded_blocks >= 0),
  ended_at timestamptz,
  updated_at timestamptz not null default now()
);
create unique index avesso_activity_sessions_one_open_idx on public.avesso_activity_sessions(user_id) where ended_at is null;
create index avesso_activity_sessions_user_started_idx on public.avesso_activity_sessions(user_id,started_at desc);

alter table public.avesso_economy_settings enable row level security;
alter table public.avesso_reward_rules enable row level security;
alter table public.avesso_wallets enable row level security;
alter table public.avesso_wallet_ledger enable row level security;
alter table public.avesso_activity_sessions enable row level security;

revoke all on public.avesso_economy_settings, public.avesso_reward_rules, public.avesso_wallets, public.avesso_wallet_ledger, public.avesso_activity_sessions from anon, authenticated;

create policy avesso_wallets_owner_read on public.avesso_wallets for select to authenticated using ((select auth.uid())=user_id);
create policy avesso_ledger_owner_read on public.avesso_wallet_ledger for select to authenticated using ((select auth.uid())=user_id);
create policy avesso_sessions_owner_read on public.avesso_activity_sessions for select to authenticated using ((select auth.uid())=user_id);

insert into public.avesso_economy_settings(id,mode,global_daily_cap,presence_block_seconds,active_window_seconds)
values('global','shadow',180,1800,120)
on conflict(id) do update set mode=excluded.mode,global_daily_cap=excluded.global_daily_cap,presence_block_seconds=excluded.presence_block_seconds,active_window_seconds=excluded.active_window_seconds;

insert into public.avesso_reward_rules(rule_key,label,category,base_amount,daily_cap,cooldown_seconds,multiplier_eligible,counts_toward_daily_cap,counts_toward_pulse,config) values
('presence_block','Presença ativa','presence',5,30,1800,true,true,true,'{}'),
('post_created','Publicação original','publication',20,60,0,true,true,true,'{}'),
('media_posted','Mídia em publicação','publication',10,20,0,true,true,true,'{}'),
('response_created','Resposta em conversa','conversation',6,36,0,true,true,true,'{}'),
('story_posted','Story publicado','stories',10,20,0,true,true,true,'{}'),
('guestbook_posted','Recado no Canto','canto',8,24,0,true,true,true,'{}'),
('plaza_session','Sessão social na Praça','plaza',12,24,900,true,true,true,'{}'),
('direct_conversation','Conversa direta qualificada','direct',10,20,0,true,true,true,'{}'),
('bonus_avatar','Primeiro avatar','identity',20,20,0,false,false,false,'{}'),
('bonus_bio','Primeira bio','identity',15,15,0,false,false,false,'{}'),
('bonus_wallpaper','Primeiro wallpaper escolhido','identity',10,10,0,false,false,false,'{}'),
('bonus_corner_music','Primeira música do Canto','identity',25,25,0,false,false,false,'{}'),
('bonus_album_photo','Primeira foto do álbum','identity',15,15,0,false,false,false,'{}'),
('bonus_first_guestbook','Primeiro recado enviado','identity',10,10,0,false,false,false,'{}'),
('weekly_present','Semana Presente','weekly',40,40,0,false,false,false,'{}'),
('weekly_avesso','Semana do Avesso','weekly',80,80,0,false,false,false,'{}'),
('legacy_post_backfill','Migração de post histórico','migration',20,0,0,false,false,false,'{}')
on conflict(rule_key) do update set label=excluded.label,category=excluded.category,base_amount=excluded.base_amount,daily_cap=excluded.daily_cap,cooldown_seconds=excluded.cooldown_seconds,multiplier_eligible=excluded.multiplier_eligible,counts_toward_daily_cap=excluded.counts_toward_daily_cap,counts_toward_pulse=excluded.counts_toward_pulse,config=excluded.config,updated_at=now();

create or replace function private.avesso_pulse_multiplier(p_user_id uuid)
returns numeric language plpgsql stable security definer set search_path='' as $$
declare v_days integer:=0; v_categories integer:=0;
begin
  select count(distinct (l.created_at at time zone 'UTC')::date),count(distinct r.category)
  into v_days,v_categories
  from public.avesso_wallet_ledger l join public.avesso_reward_rules r on r.rule_key=l.rule_key
  where l.user_id=p_user_id and l.transaction_type='earn' and l.amount>0 and r.counts_toward_pulse and l.created_at>=now()-interval '7 days';
  if v_days>=6 and v_categories>=5 then return 1.15; end if;
  if v_days>=5 and v_categories>=4 then return 1.10; end if;
  if v_days>=3 and v_categories>=3 then return 1.05; end if;
  return 1.00;
end;$$;
revoke all on function private.avesso_pulse_multiplier(uuid) from public,anon,authenticated;

create or replace function private.award_avesso_reward(p_user_id uuid,p_rule_key text,p_source_type text,p_source_id text,p_metadata jsonb,p_idempotency_key text)
returns integer language plpgsql security definer set search_path='' as $$
declare
  v_rule public.avesso_reward_rules%rowtype; v_mode text; v_global_cap integer; v_rule_today integer:=0; v_global_today integer:=0; v_multiplier numeric:=1.00; v_award integer:=0; v_inserted bigint;
begin
  if p_user_id is null then return 0; end if;
  if not exists(select 1 from public.profiles p where p.id=p_user_id) then return 0; end if;
  if public.is_user_suspended(p_user_id) then return 0; end if;
  select s.mode,s.global_daily_cap into v_mode,v_global_cap from public.avesso_economy_settings s where s.id='global';
  if coalesce(v_mode,'off')='off' then return 0; end if;
  select * into v_rule from public.avesso_reward_rules r where r.rule_key=p_rule_key and r.enabled;
  if not found or v_rule.base_amount<=0 then return 0; end if;
  insert into public.avesso_wallets(user_id) values(p_user_id) on conflict(user_id) do nothing;
  perform 1 from public.avesso_wallets w where w.user_id=p_user_id for update;
  if exists(select 1 from public.avesso_wallet_ledger l where l.idempotency_key=p_idempotency_key) then return 0; end if;
  select coalesce(sum(l.amount),0)::integer into v_rule_today from public.avesso_wallet_ledger l where l.user_id=p_user_id and l.rule_key=p_rule_key and l.transaction_type='earn' and l.created_at>=date_trunc('day',now());
  if v_rule.daily_cap>0 and v_rule_today>=v_rule.daily_cap then return 0; end if;
  if v_rule.counts_toward_daily_cap then
    select coalesce(sum(l.amount),0)::integer into v_global_today from public.avesso_wallet_ledger l join public.avesso_reward_rules r on r.rule_key=l.rule_key where l.user_id=p_user_id and l.transaction_type='earn' and l.created_at>=date_trunc('day',now()) and r.counts_toward_daily_cap;
    if v_global_cap>0 and v_global_today>=v_global_cap then return 0; end if;
  end if;
  if v_rule.multiplier_eligible then v_multiplier:=private.avesso_pulse_multiplier(p_user_id); end if;
  v_award:=round(v_rule.base_amount::numeric*v_multiplier)::integer;
  if v_rule.daily_cap>0 then v_award:=least(v_award,greatest(0,v_rule.daily_cap-v_rule_today)); end if;
  if v_rule.counts_toward_daily_cap and v_global_cap>0 then v_award:=least(v_award,greatest(0,v_global_cap-v_global_today)); end if;
  if v_award<=0 then return 0; end if;
  insert into public.avesso_wallet_ledger(user_id,transaction_type,rule_key,source_type,source_id,amount,idempotency_key,metadata)
  values(p_user_id,'earn',p_rule_key,left(p_source_type,80),left(p_source_id,180),v_award,left(p_idempotency_key,260),coalesce(p_metadata,'{}'::jsonb))
  on conflict(idempotency_key) do nothing returning id into v_inserted;
  if v_inserted is null then return 0; end if;
  update public.avesso_wallets set balance=balance+v_award,lifetime_earned=lifetime_earned+v_award,updated_at=now() where user_id=p_user_id;
  return v_award;
end;$$;
revoke all on function private.award_avesso_reward(uuid,text,text,text,jsonb,text) from public,anon,authenticated;

create or replace function private.reverse_avesso_reward(p_user_id uuid,p_original_key text,p_reason text)
returns integer language plpgsql security definer set search_path='' as $$
declare v_original public.avesso_wallet_ledger%rowtype; v_inserted bigint;
begin
  select * into v_original from public.avesso_wallet_ledger l where l.user_id=p_user_id and l.idempotency_key=p_original_key and l.transaction_type='earn';
  if not found then return 0; end if;
  perform 1 from public.avesso_wallets w where w.user_id=p_user_id for update;
  insert into public.avesso_wallet_ledger(user_id,transaction_type,rule_key,source_type,source_id,amount,idempotency_key,metadata)
  values(p_user_id,'reversal',v_original.rule_key,v_original.source_type,v_original.source_id,-v_original.amount,left('reversal:'||p_original_key,260),jsonb_build_object('reason',left(coalesce(p_reason,'reversal'),160),'original_ledger_id',v_original.id))
  on conflict(idempotency_key) do nothing returning id into v_inserted;
  if v_inserted is null then return 0; end if;
  update public.avesso_wallets set balance=greatest(0,balance-v_original.amount),lifetime_earned=greatest(0,lifetime_earned-v_original.amount),updated_at=now() where user_id=p_user_id;
  return v_original.amount;
end;$$;
revoke all on function private.reverse_avesso_reward(uuid,text,text) from public,anon,authenticated;

create or replace function private.trg_avesso_wallet_profile() returns trigger language plpgsql security definer set search_path='' as $$ begin insert into public.avesso_wallets(user_id) values(new.id) on conflict(user_id) do nothing; return new; end; $$;
revoke all on function private.trg_avesso_wallet_profile() from public,anon,authenticated;
create trigger avesso_wallet_profile_created after insert on public.profiles for each row execute function private.trg_avesso_wallet_profile();

create or replace function private.trg_avesso_post_reward() returns trigger language plpgsql security definer set search_path='' as $$
begin
  if new.reshare_post_id is null and new.reshare_photo_id is null then
    perform private.award_avesso_reward(new.author_id,'post_created','post',new.id::text,jsonb_build_object('visibility',new.visibility::text),'post_created:post:'||new.id::text);
    if new.image_url is not null or new.media_url is not null or new.media_kind is not null then perform private.award_avesso_reward(new.author_id,'media_posted','post',new.id::text,jsonb_build_object('media_kind',coalesce(new.media_kind,'')),'media_posted:post:'||new.id::text); end if;
  end if; return new;
end;$$;
revoke all on function private.trg_avesso_post_reward() from public,anon,authenticated;
create trigger avesso_post_reward after insert on public.posts for each row execute function private.trg_avesso_post_reward();

create or replace function private.trg_avesso_post_delete_reversal() returns trigger language plpgsql security definer set search_path='' as $$
begin if old.created_at>now()-interval '15 minutes' then perform private.reverse_avesso_reward(old.author_id,'post_created:post:'||old.id::text,'post_deleted_early'); perform private.reverse_avesso_reward(old.author_id,'media_posted:post:'||old.id::text,'post_deleted_early'); end if; return old; end;$$;
revoke all on function private.trg_avesso_post_delete_reversal() from public,anon,authenticated;
create trigger avesso_post_delete_reversal after delete on public.posts for each row execute function private.trg_avesso_post_delete_reversal();

create or replace function private.trg_avesso_response_reward() returns trigger language plpgsql security definer set search_path='' as $$
declare v_owner uuid; v_day text;
begin select p.author_id into v_owner from public.posts p where p.id=new.post_id; if v_owner is not null and v_owner<>new.author_id then v_day:=to_char(new.created_at at time zone 'UTC','YYYY-MM-DD'); perform private.award_avesso_reward(new.author_id,'response_created','response',new.id::text,jsonb_build_object('post_id',new.post_id),'response_created:'||new.author_id::text||':'||new.post_id::text||':'||v_day); end if; return new; end;$$;
revoke all on function private.trg_avesso_response_reward() from public,anon,authenticated;
create trigger avesso_response_reward after insert on public.responses for each row execute function private.trg_avesso_response_reward();

create or replace function private.trg_avesso_response_delete_reversal() returns trigger language plpgsql security definer set search_path='' as $$
declare v_day text; begin if old.created_at>now()-interval '15 minutes' then v_day:=to_char(old.created_at at time zone 'UTC','YYYY-MM-DD'); perform private.reverse_avesso_reward(old.author_id,'response_created:'||old.author_id::text||':'||old.post_id::text||':'||v_day,'response_deleted_early'); end if; return old; end;$$;
revoke all on function private.trg_avesso_response_delete_reversal() from public,anon,authenticated;
create trigger avesso_response_delete_reversal after delete on public.responses for each row execute function private.trg_avesso_response_delete_reversal();

create or replace function private.trg_avesso_story_reward() returns trigger language plpgsql security definer set search_path='' as $$ begin perform private.award_avesso_reward(new.author_id,'story_posted','story',new.id::text,jsonb_build_object('media_type',coalesce(new.media_type,'text')),'story_posted:story:'||new.id::text); return new; end;$$;
revoke all on function private.trg_avesso_story_reward() from public,anon,authenticated;
create trigger avesso_story_reward after insert on public.stories for each row execute function private.trg_avesso_story_reward();

create or replace function private.trg_avesso_story_delete_reversal() returns trigger language plpgsql security definer set search_path='' as $$ begin if old.created_at>now()-interval '15 minutes' then perform private.reverse_avesso_reward(old.author_id,'story_posted:story:'||old.id::text,'story_deleted_early'); end if; return old; end;$$;
revoke all on function private.trg_avesso_story_delete_reversal() from public,anon,authenticated;
create trigger avesso_story_delete_reversal after delete on public.stories for each row execute function private.trg_avesso_story_delete_reversal();

create or replace function private.trg_avesso_guestbook_reward() returns trigger language plpgsql security definer set search_path='' as $$
declare v_day text; v_count bigint;
begin v_day:=to_char(new.created_at at time zone 'UTC','YYYY-MM-DD'); perform private.award_avesso_reward(new.author_id,'guestbook_posted','guestbook',new.id::text,jsonb_build_object('profile_id',new.profile_id),'guestbook_posted:'||new.author_id::text||':'||new.profile_id::text||':'||v_day); select count(*) into v_count from public.guestbook_entries g where g.author_id=new.author_id; if v_count=1 then perform private.award_avesso_reward(new.author_id,'bonus_first_guestbook','guestbook',new.id::text,'{}'::jsonb,'bonus_first_guestbook:'||new.author_id::text); end if; return new; end;$$;
revoke all on function private.trg_avesso_guestbook_reward() from public,anon,authenticated;
create trigger avesso_guestbook_reward after insert on public.guestbook_entries for each row execute function private.trg_avesso_guestbook_reward();

create or replace function private.trg_avesso_guestbook_delete_reversal() returns trigger language plpgsql security definer set search_path='' as $$
declare v_day text; begin if old.created_at>now()-interval '15 minutes' then v_day:=to_char(old.created_at at time zone 'UTC','YYYY-MM-DD'); perform private.reverse_avesso_reward(old.author_id,'guestbook_posted:'||old.author_id::text||':'||old.profile_id::text||':'||v_day,'guestbook_deleted_early'); end if; return old; end;$$;
revoke all on function private.trg_avesso_guestbook_delete_reversal() from public,anon,authenticated;
create trigger avesso_guestbook_delete_reversal after delete on public.guestbook_entries for each row execute function private.trg_avesso_guestbook_delete_reversal();

create or replace function private.trg_avesso_profile_identity_rewards() returns trigger language plpgsql security definer set search_path='' as $$
begin
  if old.avatar_url is null and new.avatar_url is not null then perform private.award_avesso_reward(new.id,'bonus_avatar','profile',new.id::text,'{}'::jsonb,'bonus_avatar:'||new.id::text); end if;
  if trim(coalesce(old.bio,''))='' and char_length(trim(coalesce(new.bio,'')))>=10 then perform private.award_avesso_reward(new.id,'bonus_bio','profile',new.id::text,'{}'::jsonb,'bonus_bio:'||new.id::text); end if;
  if coalesce(old.profile_wallpaper,'cidade-56k')='cidade-56k' and coalesce(new.profile_wallpaper,'cidade-56k')<>'cidade-56k' then perform private.award_avesso_reward(new.id,'bonus_wallpaper','profile',new.id::text,jsonb_build_object('wallpaper',new.profile_wallpaper),'bonus_wallpaper:'||new.id::text); end if;
  if old.corner_music_url is null and new.corner_music_url is not null then perform private.award_avesso_reward(new.id,'bonus_corner_music','profile',new.id::text,'{}'::jsonb,'bonus_corner_music:'||new.id::text); end if;
  return new;
end;$$;
revoke all on function private.trg_avesso_profile_identity_rewards() from public,anon,authenticated;
create trigger avesso_profile_identity_rewards after update of avatar_url,bio,profile_wallpaper,corner_music_url on public.profiles for each row execute function private.trg_avesso_profile_identity_rewards();

create or replace function private.trg_avesso_album_photo_reward() returns trigger language plpgsql security definer set search_path='' as $$
declare v_count bigint; begin select count(*) into v_count from public.profile_photos p where p.user_id=new.user_id; if v_count=1 then perform private.award_avesso_reward(new.user_id,'bonus_album_photo','profile_photo',new.id::text,'{}'::jsonb,'bonus_album_photo:'||new.user_id::text); end if; return new; end;$$;
revoke all on function private.trg_avesso_album_photo_reward() from public,anon,authenticated;
create trigger avesso_album_photo_reward after insert on public.profile_photos for each row execute function private.trg_avesso_album_photo_reward();

create or replace function private.record_avesso_activity_heartbeat(p_user_id uuid)
returns integer language plpgsql security definer set search_path='' as $$
declare v_settings public.avesso_economy_settings%rowtype; v_last_seen timestamptz; v_session public.avesso_activity_sessions%rowtype; v_delta integer:=0; v_target_blocks integer:=0; v_reward integer:=0; v_day text;
begin
  if p_user_id is null or public.is_user_suspended(p_user_id) then return 0; end if;
  select * into v_settings from public.avesso_economy_settings where id='global'; if v_settings.mode='off' then return 0; end if;
  select p.last_seen into v_last_seen from public.profiles p where p.id=p_user_id; if v_last_seen is null or v_last_seen<now()-make_interval(secs=>v_settings.active_window_seconds) then return 0; end if;
  select * into v_session from public.avesso_activity_sessions s where s.user_id=p_user_id and s.ended_at is null for update;
  if found and (v_session.last_heartbeat_at<now()-interval '5 minutes' or (v_session.started_at at time zone 'UTC')::date<>(now() at time zone 'UTC')::date) then update public.avesso_activity_sessions set ended_at=now(),updated_at=now() where id=v_session.id; v_session.id:=null; end if;
  if v_session.id is null then insert into public.avesso_activity_sessions(user_id,started_at,last_active_at,last_heartbeat_at) values(p_user_id,now(),now(),now()) returning * into v_session; return 0; end if;
  v_delta:=least(60,greatest(0,extract(epoch from (now()-v_session.last_heartbeat_at))::integer));
  update public.avesso_activity_sessions set last_active_at=now(),last_heartbeat_at=now(),qualified_seconds=qualified_seconds+v_delta,updated_at=now() where id=v_session.id returning * into v_session;
  v_target_blocks:=floor(v_session.qualified_seconds::numeric/v_settings.presence_block_seconds)::integer;
  if v_target_blocks>v_session.rewarded_blocks then v_day:=to_char(now() at time zone 'UTC','YYYY-MM-DD'); v_reward:=private.award_avesso_reward(p_user_id,'presence_block','activity_session',v_session.id::text,jsonb_build_object('block',v_session.rewarded_blocks+1),'presence_block:'||p_user_id::text||':'||v_day||':'||(v_session.rewarded_blocks+1)::text); if v_reward>0 then update public.avesso_activity_sessions set rewarded_blocks=rewarded_blocks+1,updated_at=now() where id=v_session.id; end if; end if;
  return v_reward;
end;$$;
revoke all on function private.record_avesso_activity_heartbeat(uuid) from public,anon,authenticated;

insert into public.avesso_wallets(user_id) select p.id from public.profiles p on conflict(user_id) do nothing;

insert into public.avesso_wallet_ledger(user_id,transaction_type,rule_key,source_type,source_id,amount,idempotency_key,metadata,created_at)
select p.author_id,'earn','legacy_post_backfill','post',p.id::text,20,'legacy_post_backfill:post:'||p.id::text,jsonb_build_object('original_created_at',p.created_at),now()
from public.posts p
on conflict(idempotency_key) do nothing;

update public.avesso_wallets w
set balance=x.net,lifetime_earned=x.earned,lifetime_spent=x.spent,updated_at=now()
from (
  select u.id as user_id,
    coalesce(sum(l.amount),0)::bigint as net,
    coalesce(sum(case when l.transaction_type='earn' and l.amount>0 then l.amount else 0 end),0)::bigint as earned,
    coalesce(sum(case when l.transaction_type in ('spend','transfer_out') and l.amount<0 then -l.amount else 0 end),0)::bigint as spent
  from public.profiles u left join public.avesso_wallet_ledger l on l.user_id=u.id group by u.id
) x
where w.user_id=x.user_id;

create or replace view private.avesso_economy_shadow_audit as
select w.user_id,w.balance,w.lifetime_earned,w.lifetime_spent,
  coalesce(sum(l.amount),0)::bigint as ledger_net,
  count(l.id)::bigint as ledger_entries,
  max(l.created_at) as last_ledger_at
from public.avesso_wallets w
left join public.avesso_wallet_ledger l on l.user_id=w.user_id
group by w.user_id,w.balance,w.lifetime_earned,w.lifetime_spent;
