-- Esquema inicial aplicado ao projeto Supabase AVESSO.
-- Fonte de verdade versionada. Todas as tabelas públicas usam RLS.
create extension if not exists pgcrypto;
create type public.post_visibility as enum ('publico','privado');
create type public.support_kind as enum ('escutei','posso_ajudar','estou_aqui');
create type public.report_reason as enum ('assedio','odio','spam','risco','outro');

create table public.profiles (id uuid primary key references auth.users(id) on delete cascade,handle text not null unique check (handle ~ '^[a-z0-9_]{3,24}$'),display_name text not null check (char_length(display_name) between 2 and 50),bio text not null default '' check (char_length(bio)<=180),avatar_url text,pixel_mood text not null default 'online_demais',created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table public.posts (id uuid primary key default gen_random_uuid(),author_id uuid not null references public.profiles(id) on delete cascade,recipient_id uuid not null references public.profiles(id) on delete cascade,body text not null check (char_length(trim(body)) between 12 and 420),visibility public.post_visibility not null default 'publico',created_at timestamptz not null default now(),edited_at timestamptz,check(author_id<>recipient_id));
create table public.responses (id uuid primary key default gen_random_uuid(),post_id uuid not null references public.posts(id) on delete cascade,author_id uuid not null references public.profiles(id) on delete cascade,body text not null check(char_length(trim(body)) between 2 and 420),created_at timestamptz not null default now());
create table public.support_signals (post_id uuid not null references public.posts(id) on delete cascade,supporter_id uuid not null references public.profiles(id) on delete cascade,kind public.support_kind not null,created_at timestamptz not null default now(),primary key(post_id,supporter_id));
create table public.circles (owner_id uuid not null references public.profiles(id) on delete cascade,member_id uuid not null references public.profiles(id) on delete cascade,created_at timestamptz not null default now(),primary key(owner_id,member_id),check(owner_id<>member_id));
create table public.blocks (blocker_id uuid not null references public.profiles(id) on delete cascade,blocked_id uuid not null references public.profiles(id) on delete cascade,created_at timestamptz not null default now(),primary key(blocker_id,blocked_id),check(blocker_id<>blocked_id));
create table public.reports (id uuid primary key default gen_random_uuid(),reporter_id uuid not null references public.profiles(id) on delete cascade,post_id uuid references public.posts(id) on delete cascade,reported_profile_id uuid references public.profiles(id) on delete cascade,reason public.report_reason not null,details text not null default '' check(char_length(details)<=500),status text not null default 'aberto' check(status in('aberto','em_analise','resolvido','arquivado')),created_at timestamptz not null default now(),check(post_id is not null or reported_profile_id is not null));

create index posts_attention_order_idx on public.posts(created_at desc);create index posts_recipient_idx on public.posts(recipient_id,created_at desc);create index posts_author_idx on public.posts(author_id,created_at desc);create index responses_post_idx on public.responses(post_id,created_at);create index responses_author_idx on public.responses(author_id,created_at desc);create index circles_member_idx on public.circles(member_id);create index blocks_blocked_idx on public.blocks(blocked_id);create index reports_post_idx on public.reports(post_id) where post_id is not null;create index reports_profile_idx on public.reports(reported_profile_id) where reported_profile_id is not null;create index reports_reporter_idx on public.reports(reporter_id,created_at desc);create index support_supporter_idx on public.support_signals(supporter_id,created_at desc);

create function public.set_updated_at() returns trigger language plpgsql set search_path='' as $$begin new.updated_at=now();return new;end;$$;
create trigger profiles_set_updated_at before update on public.profiles for each row execute function public.set_updated_at();
create function public.handle_new_user() returns trigger language plpgsql security definer set search_path='' as $$declare base_handle text;final_handle text;begin base_handle:=lower(regexp_replace(coalesce(new.raw_user_meta_data->>'handle',split_part(new.email,'@',1),'pessoa'),'[^a-zA-Z0-9_]','','g'));if char_length(base_handle)<3 then base_handle:='pessoa';end if;base_handle:=left(base_handle,24);if exists(select 1 from public.profiles where handle=base_handle) then final_handle:=left(base_handle,17)||'_'||substr(new.id::text,1,6);else final_handle:=base_handle;end if;insert into public.profiles(id,handle,display_name) values(new.id,final_handle,left(coalesce(nullif(new.raw_user_meta_data->>'display_name',''),split_part(new.email,'@',1),'Pessoa'),50));return new;end;$$;
revoke all on function public.handle_new_user() from public,anon,authenticated;
create trigger on_auth_user_created after insert on auth.users for each row execute function public.handle_new_user();

create view public.feed_attention with(security_invoker=true) as select p.id,p.author_id,p.recipient_id,p.body,p.visibility,p.created_at,p.edited_at,a.handle author_handle,a.display_name author_name,a.avatar_url author_avatar,r.handle recipient_handle,r.display_name recipient_name,r.avatar_url recipient_avatar,count(distinct rs.id)::int response_count,count(distinct ss.supporter_id)::int private_support_count,(extract(epoch from(now()-p.created_at))/3600.0)/greatest(1,count(distinct rs.id)+1) attention_need from public.posts p join public.profiles a on a.id=p.author_id join public.profiles r on r.id=p.recipient_id left join public.responses rs on rs.post_id=p.id left join public.support_signals ss on ss.post_id=p.id where p.visibility='publico' group by p.id,a.id,r.id;

alter table public.profiles enable row level security;alter table public.posts enable row level security;alter table public.responses enable row level security;alter table public.support_signals enable row level security;alter table public.circles enable row level security;alter table public.blocks enable row level security;alter table public.reports enable row level security;
create policy profiles_public_read on public.profiles for select to anon,authenticated using(true);create policy profiles_owner_update on public.profiles for update to authenticated using((select auth.uid())=id) with check((select auth.uid())=id);
create policy posts_public_read on public.posts for select to anon,authenticated using(visibility='publico' or(select auth.uid())=author_id or(select auth.uid())=recipient_id);create policy posts_author_insert on public.posts for insert to authenticated with check((select auth.uid())=author_id and author_id<>recipient_id);create policy posts_author_update on public.posts for update to authenticated using((select auth.uid())=author_id) with check((select auth.uid())=author_id and author_id<>recipient_id);create policy posts_author_delete on public.posts for delete to authenticated using((select auth.uid())=author_id);
create policy responses_visible_with_post on public.responses for select to anon,authenticated using(exists(select 1 from public.posts p where p.id=post_id and(p.visibility='publico' or p.author_id=(select auth.uid()) or p.recipient_id=(select auth.uid()))));create policy responses_author_insert on public.responses for insert to authenticated with check((select auth.uid())=author_id);create policy responses_author_update on public.responses for update to authenticated using((select auth.uid())=author_id) with check((select auth.uid())=author_id);create policy responses_author_delete on public.responses for delete to authenticated using((select auth.uid())=author_id);
create policy support_parties_read on public.support_signals for select to authenticated using((select auth.uid())=supporter_id or exists(select 1 from public.posts p where p.id=post_id and((select auth.uid()) in(p.author_id,p.recipient_id))));create policy support_self_insert on public.support_signals for insert to authenticated with check((select auth.uid())=supporter_id);create policy support_self_update on public.support_signals for update to authenticated using((select auth.uid())=supporter_id) with check((select auth.uid())=supporter_id);create policy support_self_delete on public.support_signals for delete to authenticated using((select auth.uid())=supporter_id);
create policy circles_owner_read on public.circles for select to authenticated using((select auth.uid())=owner_id);create policy circles_owner_insert on public.circles for insert to authenticated with check((select auth.uid())=owner_id);create policy circles_owner_delete on public.circles for delete to authenticated using((select auth.uid())=owner_id);create policy blocks_owner_all on public.blocks for all to authenticated using((select auth.uid())=blocker_id) with check((select auth.uid())=blocker_id);create policy reports_owner_insert on public.reports for insert to authenticated with check((select auth.uid())=reporter_id);create policy reports_owner_read on public.reports for select to authenticated using((select auth.uid())=reporter_id);
grant usage on schema public to anon,authenticated;grant select on public.profiles,public.posts,public.responses,public.feed_attention to anon,authenticated;grant insert,update,delete on public.profiles,public.posts,public.responses,public.support_signals,public.circles,public.blocks,public.reports to authenticated;grant select on public.support_signals,public.circles,public.blocks,public.reports to authenticated;alter publication supabase_realtime add table public.posts,public.responses;
